### ISSUE TITLE
Precompilation

### ISSUE THREAD

**Issue by lssimoes** [prcastro/NeuralNetsLite.jl#11]
Should we add the line 

```
VERSION >= v"0.4.0-dev+6521" && __precompile__(true)
```

to the beginning of the module file ([NeuralNetsLite.jl](https://github.com/prcastro/NeuralNetsLite.jl/blob/master/src/NeuralNetsLite.jl#L1) file) so that the Module is precompiled?
What can we benefit on doing this?

**Comment by prcastro** [comment]
Done
