### ISSUE TITLE
Documentation

### ISSUE THREAD

**Issue by prcastro** [prcastro/NeuralNetsLite.jl#8]
Not only insert a nice/helpful docstring on each function/type, but also document the interface expected by the package (how to create new error/activation functions, etc) and conceptually how it works (like a PDF deriving the algorithm).
- [x] Docstrings
- [x] README
- [x] Interface documentation
- [x] Conceptual PDF

**Comment by lssimoes** [comment]
I'd like to write this PDF explaining the concepts behind the implementation, if I may

**Comment by prcastro** [comment]
Go ahead
